version: '3.7'
services:
  nginx:
    build:
      context: .
      dockerfile: ./compose/local/nginx/Dockerfile
    container_name: watcha_nginx
    depends_on:
      - watcha
      - db
    ports:
      - "80:80"
    links:
      - watcha
    networks:
      - watcha_network

  watcha:
    build:
      dockerfile: ./compose/local/backend/Dockerfile
      context: .
    container_name: watcha_backend
    ports:
      - '13014:13014'
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
    env_file:
      - compose/dev/dev.env
    links:
      - db
    depends_on:
      - db
    networks:
      - watcha_network

  db:
    image: mysql:8.0.23
    restart: unless-stopped
    container_name: watcha_mysql
    platform: linux/x86_64
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql/sqls/:/docker-entrypoint-initdb.d/
    env_file:
      - compose/dev/mysql.env
    networks:
      - watcha_network

networks:
  watcha_network:
    driver: bridge