version: "3"
services:
  watcha-redis:
    container_name: watcha-redis
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - watcha-redis:/data
    command: redis-server --requirepass foobared

volumes:
  watcha-redis:
