version: '3.7'
services:
  nginx:
    build:
      context: .
      dockerfile: ./compose/dev/nginx/Dockerfile
    container_name: watcha_nginx
    ports:
      - "80:80"
    depends_on:
      - watcha_backend
      - db
    links:
      - watcha_backend

  watcha_backend:
    build:
      dockerfile: ./compose/local/backend/Dockerfile
      context: .
    container_name: watcha_backend
    ports:
      - '13014:13014'
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
    env_file:
      - compose/dev/dev.env
    links:
      - db
    depends_on:
      - db

  db:
    image: mysql:8.0.23
    restart: unless-stopped
    container_name: watcha_mysql
    platform: linux/x86_64
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql/sqls/:/docker-entrypoint-initdb.d/
    env_file:
      - compose/dev/mysql.env
    healthcheck:
      test: ["CMD", "mysql", "-h", "127.0.0.1", "-u", "nest_watcha", "-p", "xnaoqyuraoqwuyr", "-e", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
