version: '3.7'
services:
  nginx:
    build:
      context: .
      dockerfile: ./compose/local/nginx/Dockerfile
    depends_on:
      - group_up
      - db
    ports:
      - "80:80"
    links:
      - group_up

  group_up:
    build:
      dockerfile: ./compose/local/backend/Dockerfile
      context: .
    ports:
      - '8000:8000'
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
    env_file:
      - compose/local/dev.env
    links:
      - db
    depends_on:
      - db

  db:
    image: mysql:8.0.23
    restart: unless-stopped
    container_name: group_up_mysql
    platform: linux/x86_64
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql/sqls/:/docker-entrypoint-initdb.d/
    env_file:
      - compose/local/mysql.env