version: '3.7'
services:
  nginx:
    build:
      context: .
      dockerfile: ./compose/dev/nginx/Dockerfile
    container_name: watcha_nginx
    depends_on:
      - nest_watcha
      - db
    ports:
      - "80:80"
    links:
      - nest_watcha

  nest_watcha:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: watcha_backend
    environment:
      - TZ=Asia/Seoul
    ports:
      - '13014:13014'
    env_file:
      - compose/dev/dev.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - db
    depends_on:
      - db
    networks:
      - watcha

  db:
    image: mysql:8.0.23
    restart: unless-stopped
    container_name: watcha_mysql
    platform: linux/x86_64
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql/sqls/:/docker-entrypoint-initdb.d/
    env_file:
      - compose/dev/mysql.env
