version: "3.7"
services:
  nestjs:
    container_name: "nest_api_${NODE_ENV}"
    image: "nest_api_${NODE_ENV}"
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - /app/node_modules